version: '3.1'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.3.2
    restart: always
    #volumes:
      #- ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - MARIADB_DATABASE=db
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123456789
    ports:
      - "3308:3306"

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - 8080:8080